export class User{
    userId: number;
	userName: string;
	email: string;
	password: string;
	accessLevel: number;
	canChangePassword: number;
	isTestUser: boolean;
	lastName: string;
	firstName: string;
	isDemo: boolean;
	categories: string;
	sessionCookie: string;
	pipelineEntriesPerPage: number;
	columnPreferences: string;
	forceLogout: boolean;
	title: string;
	workNumber: string;
	cellNumber: string;
	otherNumber: string;
	address: string;
	notes: string;
	company: string;
	city: string;
	state: string;
	zip: string;
	country: string;
	canSeeEeoInfo: boolean;
}